server:
  port: 8089
eureka:
   client:
     register-with-eureka: true
     serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: currency-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true 
          lower-case-service-id: true 
      routes:
        - id: currency-exchange-service
          uri: lb://currency-exchange-service
          predicates:
            - Path=/**
        - id: currency-conversion-service
          uri: lb://currency-conversion-service
          predicates:
            - Path=/**
            
